name: watermelon
description: Flutter版合成大西瓜

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.2
  flame: 1.0.0-rc6
  flame_forge2d: 0.6.2-rc3
  path_provider: ^1.6.27
  hive: ^1.4.4+1
  sensors: ^0.4.2+6
  url_launcher: ^5.7.10
  image_picker: ^0.6.7+22
  image_picker_web_redux: ^1.1.3
  share_plus: ^1.2.0
  flame_audio:
    git:
      url: https://github.com/idootop/flame_audio.git
      ref: 576c7cd
  crop:
    git:
      url: https://github.com/idootop/flutter_crop.git
      ref: circle
  image:
    git:
      url: https://github.com/idootop/image.git
      ref: crop
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/images/friuts/
    - assets/images/qq/
    - assets/images/985/
    - assets/images/shandong/

flutter_icons:
  image_path: "logo.png"
  android: true
  ios: true